#!/usr/bin/env python3
#Purpose is to gether User IP
#gather User Input
user_input = input('Please enter an IPv4 IP address:')

#display user input
print("You told me the IPv4 address is:" + user_input)

#get vendor information
user_input = input("Please enter Vendor Name:")

#Display vendor information
print("You told me the Vendor is:" + user_input)

